[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  CI = "false"

[plugins]
  package = "@netlify/plugin-ignore-build-step"

[functions]
  node_bundler = "esbuild"

[optimize]
  # disable secret scanning fully
  secrets_scan_enabled = false
